server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/llawliet1945/assessment-bvk-config-server.git
          skipSslValidation: true
          clone-on-start: true
          timeout: 10
          username: llawliet1945
          password: 180699aa
          default-label: main
          ignore-local-ssh-settings: false
          refresh-rate: 300