spring:
  application:
    name: api-gateway
  profiles:
    active: development
  cloud:
    config:
      uri: http://${CONFIG_HOST:localhost}:8888
      fail-fast: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
