server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    config:
      server:
        git:
          uri: https://github.com/llawliet1945/assessment-bvk-config-server.git
          skipSslValidation: true
          clone-on-start: true
          timeout: 10
          default-label: main
          ignore-local-ssh-settings: false
          refresh-rate: 300