server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      default-filters:
        - name: CostumFilter
      routes:
        - id: auth-server
          uri: lb://auth-server
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: user-server
          uri: lb://user-server
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
        - id: transaction-server
          uri: lb://transaction-server
          predicates:
            - Path=/transaction/**
          filters:
            - StripPrefix=1