server:
  port: 8083
spring:
  application:
    name: transaction-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/llawliet1945/assessment-bvk-config-server.git
          skipSslValidation: true
          clone-on-start: true
          timeout: 10
          default-label: main
          ignore-local-ssh-settings: false
          refresh-rate: 300
  datasource:
    password: admin
    username: postgres
    url: jdbc:postgresql://localhost:5432/assessment
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 10
      max-lifetime: 30000
      minimum-idle: 5
      connection-timeout: 20000
  jpa:
    show-sql: true